server:
  port: 9000
  servlet:
    context-path: /
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    Member:
      path: /Member/**
      serviceId: memberservice
      sensitiveHeaders:
    Order:
      path: /Market/**
      serviceId: marketservice
      sensitiveHeaders:
    Pays:
      path: /Pays/**
      serviceId: payservice
      sensitiveHeaders:
    PayMents:
      path: /PayMents/**
      serviceId: paymentsservice
      sensitiveHeaders:
    IntegralMall:
      path: /IntegralMall/**
      serviceId: integralservice
      sensitiveHeaders:

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Xx960928++
    url: jdbc:mysql://rm-bp19258xs6rg675x91o.mysql.rds.aliyuncs.com:3306/armylife?serverTimezone=UTC
    hikari:
      max-lifetime: 8
  cloud:
    nacos:
      discovery:
        server-addr: 118.31.121.141:8848
        ip: 129.211.72.16
  application:
    name: zuul
  redis:
    host: 118.31.121.141
    password: Kzr20190603.
    port: 6379
    timeout: 86400s
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
    timeout: 86400s
management:
  endpoints:
    web:
      exposure:
        include: "*"
base-path: /
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000