server:
  port: 9132
spring:
  profiles:
    active: prod
  application:
    name: integralservice
  cloud:
    nacos:
      discovery:
        server-addr: 118.31.121.141:8848
        ip: 129.211.72.16
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
    timeout: 86400s
  redis:
    host: 118.31.121.141
    password: Kzr20190603.
    port: 6379
    timeout: 86400s
    test-on-borrow: true
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp19258xs6rg675x91o.mysql.rds.aliyuncs.com:3306/armylife?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: Xx960928++
    hikari:
      max-lifetime: 0
#logging:
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    root: warn
    cn.armylife.payments.Mapper: debug
    com.alibaba.nacos.client.naming: error
