server:
  port: 10001
spring:
  profiles:
    active: dev
  application:
    name: marketservice
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
    timeout: 86400s
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 86400s
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 127.0.0.1:3306/armylife?serverTimezone=UTC
    username: root
    password: root
    hikari:
      max-lifetime: 0
#logging:
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  level:
    root: warn
    cn.armylife.payments.Mapper: debug
    com.alibaba.nacos.client.naming: error
