server:
  port: 9122
spring:
  profiles:
    active: dev
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 127.0.0.1:3306/armylife?serverTimezone=UTC
    username: root
    password: root
    hikari:
      max-lifetime: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8718
  session:
    redis:
      namespace: spring:session
      flush-mode: on_save
    store-type: Redis
    timeout: 3600s
  redis:
    timeout: 3600s
    port: 6379
    host: 118.31.121.141
    password: Kzr20190603.
  application:
    name: payservice
  aop:
    auto: true
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    cn.armylife.payments.Mapper: debug
    com.alibaba.nacos.client.naming: error
#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 90000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000