server:
  port: 9121
spring:
  profiles:
    active: prod
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp19258xs6rg675x91o.mysql.rds.aliyuncs.com:3306/union?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: Xx960928++
    hikari:
      max-lifetime: 0
  cloud:
    nacos:
      discovery:
        server-addr: 118.31.121.141:8848
        ip: 129.211.72.16
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: 127.0.0.1:8718
  session:
    redis:
      namespace: spring:session
      flush-mode: on_save
    store-type: Redis
    timeout: 3600s
  redis:
    timeout: 3600s
    port: 6379
    host: 118.31.121.141
    password: Kzr20190603.
  application:
    name: unionservice
  aop:
    auto: true
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
