server:
  port: 9121
spring:
  profiles:
    active: dev
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  thymeleaf:
    cache: false
    prefix:
      classpath: /templates
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/union?serverTimezone=UTC
    username: root
    password: root
    hikari:
      max-lifetime: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: e9b9f971-7391-4692-b9ae-50b00ab26924
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8718
  session:
    redis:
      namespace: spring:session
      flush-mode: on_save
    store-type: Redis
    timeout: 3600s
  redis:
    timeout: 3600s
    port: 6379
    host: 118.31.121.141
    password: Kzr20190603.
  application:
    name: unionservice
  aop:
    auto: true
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    root: warn